name: Playwright Tests with Allure

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      #  Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      #  Install dependencies
      - name: Install dependencies
        run: npm ci

      #  Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      #  Clean Allure folders (results + report)
      - name: Clean Allure folders
        run: rm -rf allure-results allure-report

      #  Run Playwright tests
      - name: Run Playwright tests
        run: npm run test

      #  Install Allure CLI globally
      - name: Install Allure CLI
        run: npm install -g allure-commandline@2.21.0 --save-dev

      #  Generate Allure report
      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      #  Upload Allure report as artifact
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      # Deploy Allure report to GitHub Pages
      - name: Deploy Allure report
        uses: peaceiris/actions-gh-pages@v4
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }} 
         publish_dir: ./allure-report/*
         publish_branch: gh-pages
         user_name: github-actions
         user_email: github-actions@github.com
